### ISSUE TITLE
World rollback when using warp command

### ISSUE THREAD

**Issue by skorzanydran** [Drew-Chase/The-Warp-Mod#1]
When I move from one warp to another and vice versa, the world changes are not saved. So, taking something from the chest on the warp, moving to another warp and returning back, the same items appeared in the chest that I recently took. At the same time, things do not disappear in my inventory.

**Comment by Drew-Chase** [comment]
My warp mod uses built in minecraft teleporting function to operate.  That kind of issue couldn't be caused solely by the warp mod.  I would run a debug on the server to make sure that nothing is preventing from chunk saving.
